# Generated by Django 4.0.3 on 2022-03-14 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=150)),
                ('car_model', models.CharField(max_length=150)),
                ('power', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('id_psn', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('points', models.CharField(blank=True, choices=[('P1', '25'), ('P2', '18'), ('P3', '15'), ('P4', '12'), ('P5', '10'), ('P6', '8'), ('P7', '6'), ('P8', '4'), ('P9', '2'), ('P10', '1')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.CharField(blank=True, choices=[('P1', '25'), ('P2', '18'), ('P3', '15'), ('P4', '12'), ('P5', '10'), ('P6', '8'), ('P7', '6'), ('P8', '4'), ('P9', '2'), ('P10', '1')], max_length=3)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='camp.car')),
                ('pilot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='camp.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(blank=True, choices=[('P1', '25'), ('P2', '18'), ('P3', '15'), ('P4', '12'), ('P5', '10'), ('P6', '8'), ('P7', '6'), ('P8', '4'), ('P9', '2'), ('P10', '1')], max_length=3)),
                ('cars', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='camp.car')),
                ('pilots', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='camp.pilot')),
                ('teams', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='camp.team')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='pilot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='camp.pilot'),
        ),
    ]
