# Generated by Django 4.0.4 on 2022-05-18 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=150)),
                ('car_model', models.CharField(max_length=150)),
                ('power', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('id_psn', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('points', models.CharField(blank=True, choices=[(25, 'P1'), (18, 'P2'), (15, 'P3'), (12, 'P4'), (10, 'P5'), (8, 'P6'), (6, 'P7'), (4, 'P8'), (2, 'P9'), (1, 'P10'), (0, 'not_point')], default='not_point', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.CharField(blank=True, choices=[(25, 'P1'), (18, 'P2'), (15, 'P3'), (12, 'P4'), (10, 'P5'), (8, 'P6'), (6, 'P7'), (4, 'P8'), (2, 'P9'), (1, 'P10'), (0, 'not_point')], default='not_point', max_length=3)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='camp.car')),
                ('pilots', models.ManyToManyField(to='camp.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cars', models.ManyToManyField(to='camp.car')),
                ('pilots', models.ManyToManyField(to='camp.pilot')),
                ('teams', models.ManyToManyField(to='camp.team')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='pilots',
            field=models.ManyToManyField(related_name='pilot', to='camp.pilot'),
        ),
    ]
