# Generated by Django 4.0.3 on 2022-03-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pilots',
            field=models.ManyToManyField(related_name='pilot', to='camp.pilot'),
        ),
    ]
