# Generated by Django 4.0.3 on 2022-03-01 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(choices=[('P1', '25'), ('P2', '18'), ('P3', '15'), ('P4', '12'), ('P5', '10'), ('P6', '8'), ('P7', '6'), ('P8', '4'), ('P9', '2'), ('P10', '1')], max_length=3)),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camp.car', unique=True)),
                ('pilots', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camp.pilot', unique=True)),
                ('teams', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camp.team', unique=True)),
            ],
        ),
    ]
