# Generated by Django 4.0.3 on 2022-03-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_alter_car_pilots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='pilot',
        ),
        migrations.AddField(
            model_name='team',
            name='pilots',
            field=models.ManyToManyField(to='camp.pilot'),
        ),
    ]
