# Generated by Django 4.0.3 on 2022-03-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_alter_car_pilot_alter_grid_cars_alter_grid_pilots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='number',
            field=models.IntegerField(),
        ),
    ]
