# Generated by Django 4.0.3 on 2022-03-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_remove_team_pilot_team_pilots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='points',
            field=models.CharField(blank=True, choices=[(25, 'P1'), (18, 'P2'), (15, 'P3'), (12, 'P4'), (10, 'P5'), (8, 'P6'), (6, 'P7'), (4, 'P8'), (2, 'P9'), (1, 'P10')], default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.CharField(blank=True, choices=[(25, 'P1'), (18, 'P2'), (15, 'P3'), (12, 'P4'), (10, 'P5'), (8, 'P6'), (6, 'P7'), (4, 'P8'), (2, 'P9'), (1, 'P10')], default=0, max_length=3),
        ),
    ]
